version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.1
  aws-cli: circleci/aws-cli@1.1.0

jobs:
  build:
    executor: aws-cli/default
    # environment:
    #   DOCKER_BUILDKIT: 1 # not supported by CircleCI daemon
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-ecr/build-and-push-image:
          region: AWS_DEFAULT_REGION
          repo: tier/${CIRCLE_PROJECT_REPONAME} # we prepare the repositories elsewhere
          tag: ${CIRCLE_SHA1:0:8},latest-${CIRCLE_BRANCH//\//-}

workflows:
  version: 2
  build_and_push:
    jobs:
    - build:
        context: global-production
        filters:
            branches:
              only: master
